Optimized controllers, swagger UI authorization added
ABolodurin/SocialMedia pull request #1
Opened 2023-09-26 14:24 UTC by ABolodurin

2023-09-26 15:10 UTC, alexanderbrun commented
- [ ] прочитать по git flow - основная модель ветвления, которая, в том или ином виде используется везде. Попробовать создать тестовый проект с несколькими ветками по git flow. Запоминить как именовать ветки по  git flow

2023-09-26 16:41 UTC, alexanderbrun commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
> +                .securitySchemes(List.of(apiKey()))
что нам дают эти 2 настройки?

2023-09-26 16:42 UTC, alexanderbrun commented on api-docs.json
> +{"swagger":"2.0","info":{"description":"Social media API pet project","version":"1.0","title":"Social media","contact":{"name":"Aleksandr Bolodurin","url":"https://t.me/bandit26","email":"shur026@yan
нужно json привести в неуродливое состояние

2023-09-26 16:44 UTC, alexanderbrun commented
- [ ] переделать application.properties в application.yml - более удобный, современный и популярный формат

2023-09-26 16:45 UTC, alexanderbrun commented
`spring.jpa.hibernate.ddl-auto = create-drop` - убрать. От этого рекомендуется избавляться, когда приложение уже оформилось во что-то более-менее серьезное.
Лучше переделать так чтобы запускалось без поднятой постгри на машине (можно хотябы дернуть контроллеры, зайти в сваггер)
Нужны отдельные ликвибейс скрипты (SQL, не XML) на создание базы + инструкция в ридми как их накатить.
create-drop можно оставить для тестов или лучше в тестах накатывать аналогичные ликви скрипты

2023-09-26 16:49 UTC, alexanderbrun commented
`private static final long EXPIRATION_TIME_MILLS = 1000 * 60 * 24; //24 hours`
если это миллисекунды в сутках то формула неправильная)

2023-09-26 16:50 UTC, alexanderbrun commented
в ридми: 
SpringFox (Swagger) 3.0.0
- вообще у тебя свагер 2, так что это может в заблуждение ввести

2023-09-26 16:52 UTC, alexanderbrun commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
>      private ApiInfo metaInfo() {
текстовые данные лучше занести и тянуть из application.yml (application.properties)

2023-09-26 16:53 UTC, alexanderbrun commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
>                  .apis(RequestHandlerSelectors.basePackage("ru.bolodurin.socialmedia"))
лучше указать именно пакет с контроллерами

2023-09-26 16:53 UTC, alexanderbrun commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
> +        return new ApiKey("JWT(Bearer + token)", "Authorization", "header");
лучше занести текстовки в константы

2023-09-27 04:11 UTC, ABolodurin commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
> +                .securitySchemes(List.of(apiKey()))
Обе настройки для UI. ApiInfo добавляет заголовок с инфо на главной странице(слева сверху), securitySchemes  добавляет окно авторизации(над описанием контроллеров справа)

2023-09-28 07:39 UTC, ABolodurin commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
>      private ApiInfo metaInfo() {
эти не получится, аннотация требует константы

2023-09-28 07:51 UTC, ABolodurin commented on src/main/java/ru/bolodurin/socialmedia/configuration/SwaggerConfig.java
> +        return new ApiKey("JWT(Bearer + token)", "Authorization", "header");
done

2023-10-03 07:31 UTC, ABolodurin commented on api-docs.json
> +{"swagger":"2.0","info":{"description":"Social media API pet project","version":"1.0","title":"Social media","contact":{"name":"Aleksandr Bolodurin","url":"https://t.me/bandit26","email":"shur026@yan
done

2023-10-11 16:48 UTC, alexanderbrun commented on src/main/resources/application.yml
> +      matching-strategy: ANT_PATH_MATCHER
это нам зачем необходимо?

2023-10-11 16:51 UTC, alexanderbrun commented
- [ ] нужно поменять target (base branch) на develop. Предварительно из девелопа откатить коммиты этой ветки. Мы должны вливать сначала в девелоп. А у нас получилось что этот ПР уже влит в дев

2023-10-11 16:52 UTC, alexanderbrun approved these changes

2023-10-11 16:53 UTC, alexanderbrun requested changes
нужно поменять target (base branch) на develop. Предварительно из девелопа откатить коммиты этой ветки. Мы должны вливать сначала в девелоп. А у нас получилось что этот ПР уже влит в дев

2023-10-18 08:50 UTC, closed without merging